Add Ruby 3.3 and Ruby next to matrix
cucumber/cucumber-expressions pull request #272
Opened 2024-01-25 20:17 UTC by pirj

### 🤔 What's changed?

Add the recently released Ruby 3.3 and Ruby next to matrix

### ⚡️ What's your motivation? 

Some weird failures happen with ruby-head https://github.com/rspec/rspec-mocks/actions/runs/7659693178/job/20875374161?pr=1477

Apparently, `bigdecimal` now needs to be explicitly declared as a dependency in ruby-head

To check that, we need a ruby-head build.

### 🏷️ What kind of change is this?

- :support:

### ♻️ Anything particular you want feedback on?

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

2024-02-15 20:07 UTC, mpkorstanje requested changes
I'm happy with `3.3` but I'd rather not test against development versions. It generates too much noise and instability.

@luke-hill any second opinions?

2024-02-16 08:10 UTC, luke-hill commented
I agree about not using ruby-head.
I also agree there are some odd failures. Although head is essentially 3.4 and I know some gems are being altered by default with each new ruby.

It's something to add to "the list"

I think I also need to start getting 3.3 on the other CI systems

2024-02-16 10:01 UTC, pirj commented
Please consider this PR just a demonstration of the issue with bigdecimal.

2024-02-16 10:01 UTC, closed without merging

2024-02-16 10:06 UTC, luke-hill commented
Thanks for the help. It is greatly appreciated. I'll get on this soon